# Generated by Django 3.1.7 on 2021-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(blank=True, max_length=255)),
                ('main_post_user', models.CharField(blank=True, max_length=255)),
                ('main_post_title', models.CharField(blank=True, max_length=255)),
                ('comments', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=',', max_length=255)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=' ', max_length=255)),
                ('title', models.CharField(default='', max_length=100)),
                ('message', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NickUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('discord_member', models.BooleanField(default=False)),
                ('discord_name', models.CharField(blank=True, max_length=255)),
                ('supporter', models.BooleanField(default=False)),
                ('special', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirm', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, unique=True)),
                ('discord_member', models.BooleanField(default=False)),
                ('discord_name', models.CharField(blank=True, max_length=255)),
                ('special', models.BooleanField(default=False)),
                ('special_roles', models.CharField(blank=True, max_length=255)),
                ('long_supporter', models.BooleanField(default=False)),
                ('muffin_family', models.BooleanField(default=False)),
                ('muffin_role', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
