# Generated by Django 3.2 on 2021-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='Post_Tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='Post_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='Post_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
