# Generated by Django 3.1.7 on 2021-03-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='user',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
