# Generated by Django 3.1.7 on 2021-03-26 19:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20210325_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fa_list',
            field=models.ManyToManyField(blank=True, related_name='fa_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='friend',
        ),
    ]
