# Generated by Django 3.1.7 on 2021-02-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_nickuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='nickuser',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
