# Generated by Django 3.1.7 on 2021-03-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210310_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='discord_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='long_supporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='muffin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='special',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='special_roles',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
