# Generated by Django 3.1.7 on 2021-03-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_forum_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_test',
            name='user',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
