# Generated by Django 3.1.7 on 2021-03-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20210301_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='nickuser',
            name='discord_name',
            field=models.CharField(max_length=255),
        ),
    ]
