# Generated by Django 3.1.7 on 2021-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20210310_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='muffin',
            new_name='muffin_family',
        ),
        migrations.AddField(
            model_name='profile',
            name='muffin_role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
