# Generated by Django 3.1.7 on 2021-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_nickuser_discord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickuser',
            name='discord_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
