# Generated by Django 3.1.7 on 2021-03-15 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20210315_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='User',
            new_name='Username',
        ),
    ]
