# Generated by Django 3.1.7 on 2021-03-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20210315_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Username',
            new_name='User',
        ),
    ]
